source "https://api.berkshelf.com"

cookbook 'system', git: 'https://github.com/xhost-cookbooks/system'
cookbook 'nginx', git: 'https://github.com/phlipper/chef-nginx'
cookbook 'rvm', git: 'https://github.com/fnichol/chef-rvm'
cookbook 'java', '~> 1.29.0'
cookbook 'elasticsearch', git: 'https://github.com/elasticsearch/cookbook-elasticsearch'
cookbook 'graphite', git: 'git://github.com/hw-cookbooks/graphite.git'
# cookbook 'collectd', git: 'https://github.com/miah/chef-collectd'
cookbook 'collectd', git: 'https://github.com/coderanger/chef-collectd'
cookbook 'apache2', git: 'https://github.com/viverae-cookbooks/apache2'
cookbook 'statsd',   git: 'git://github.com/hectcastro/chef-statsd.git'
cookbook 'user', git: 'https://github.com/fnichol/chef-user'

cookbook 'base',              :path => 'site-cookbooks/base'
cookbook 'hosts',             :path => 'site-cookbooks/hosts'
cookbook 'ssd',               :path => 'site-cookbooks/ssd'
cookbook 'mongodb',           :path => 'site-cookbooks/mongodb'
cookbook 'glusterfs',         :path => 'site-cookbooks/glusterfs'
cookbook 'collectd_graphite', :path => 'site-cookbooks/collectd_graphite'
cookbook 'oracle_jdk_8',      :path => 'site-cookbooks/oracle_jdk_8'
cookbook 'ruby',              :path => 'site-cookbooks/ruby'
cookbook 'apache_auth',       :path => 'site-cookbooks/apache_auth'
cookbook 'iptables',          :path => 'site-cookbooks/iptables'
cookbook 'app',               :path => 'site-cookbooks/app'
cookbook 'time',              :path => 'site-cookbooks/time'
